using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace PetBuddies_API.Infrastructure.Data.Migrations
{
    /// <inheritdoc />
    public partial class ajustar_identidade_do_catalogo_semeado : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // O seed gravou ids explícitos e o gerador ficou em 1: sem isto, o primeiro POST colide na PK.
            migrationBuilder.Sql("ALTER TABLE T_PB_PROTOCOLO MODIFY (ID_PROTOCOLO GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))");
            migrationBuilder.Sql("ALTER TABLE T_PB_REGRA_PROTOCOLO MODIFY (ID_REGRA_PROTOCOLO GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
