// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetBuddies_API.Infrastructure.Data;

#nullable disable

namespace PetBuddies_API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260909225915_remover_registro_clinico")]
    partial class remover_registro_clinico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetBuddies_API.Domain.Entities.OfertaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_OFERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TP_ATO");

                    b.Property<int>("ClinicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_INICIO_VIGENCIA");

                    b.Property<long?>("ProtocoloId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PROTOCOLO");

                    b.Property<string>("Subtipo")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_SUBTIPO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("NUMBER(10,2)")
                        .HasColumnName("NR_VALOR");

                    b.HasKey("Id")
                        .HasName("PK_T_PB_OFERTA");

                    b.HasIndex("ProtocoloId");

                    b.HasIndex("ClinicaId", "Ato", "Subtipo", "ProtocoloId", "InicioVigencia")
                        .IsUnique()
                        .HasDatabaseName("UX_OFERTA_VIGENCIA");

                    b.ToTable("T_PB_OFERTA", null, t =>
                        {
                            t.HasCheckConstraint("CK_OFERTA_ALVO", "(TP_ATO IN ('PROCEDIMENTO','CONSULTA') AND TP_SUBTIPO IS NOT NULL AND ID_PROTOCOLO IS NULL) OR (TP_ATO = 'PROTOCOLO' AND ID_PROTOCOLO IS NOT NULL AND TP_SUBTIPO IS NULL)");

                            t.HasCheckConstraint("CK_OFERTA_ATO", "TP_ATO IN ('PROCEDIMENTO','CONSULTA','PROTOCOLO')");

                            t.HasCheckConstraint("CK_OFERTA_VALOR", "NR_VALOR >= 0");
                        });
                });

            modelBuilder.Entity("PetBuddies_API.Domain.Entities.ProtocoloEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PROTOCOLO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("AT_ATIVO");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_CATEGORIA_PROTOCOLO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ES_ESPECIE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NM_NOME");

                    b.HasKey("Id")
                        .HasName("PK_T_PB_PROTOCOLO");

                    b.ToTable("T_PB_PROTOCOLO", null, t =>
                        {
                            t.HasCheckConstraint("CK_PROTOCOLO_ATIVO", "AT_ATIVO IN (0,1)");

                            t.HasCheckConstraint("CK_PROTOCOLO_CATEGORIA", "TP_CATEGORIA_PROTOCOLO IN ('PREVENTIVO','POS_CIRURGICO')");

                            t.HasCheckConstraint("CK_PROTOCOLO_ESPECIE", "ES_ESPECIE IN ('CACHORRO','GATO','PASSARO','COELHO','HAMSTER','OUTRO')");
                        });
                });

            modelBuilder.Entity("PetBuddies_API.Domain.Entities.RegraPontuacaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGRA_PONTUACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Gesto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TP_GESTO");

                    b.Property<DateTime>("InicioVigencia")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_INICIO_VIGENCIA");

                    b.Property<int>("Pontos")
                        .HasPrecision(5)
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("NR_PONTOS");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id")
                        .HasName("PK_T_PB_REGRA_PONTUACAO");

                    b.HasIndex("ClinicaId", "Gesto", "InicioVigencia")
                        .IsUnique()
                        .HasDatabaseName("UK_PONTUACAO_VIGENCIA");

                    b.ToTable("T_PB_REGRA_PONTUACAO", null, t =>
                        {
                            t.HasCheckConstraint("CK_PONTUACAO_GESTO", "TP_GESTO IN ('PLANO_CRIADO','CONSULTA_AGENDADA','CONSULTA_REALIZADA','PROCEDIMENTO_EXECUTADO')");

                            t.HasCheckConstraint("CK_PONTUACAO_PONTOS", "NR_PONTOS > 0");
                        });
                });

            modelBuilder.Entity("PetBuddies_API.Domain.Entities.RegraProtocoloEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_REGRA_PROTOCOLO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DataBase")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TP_DATA_BASE");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<int?>("Intervalo")
                        .HasPrecision(4)
                        .HasColumnType("NUMBER(4)")
                        .HasColumnName("NR_INTERVALO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NM_NOME");

                    b.Property<int>("Offset")
                        .HasPrecision(4)
                        .HasColumnType("NUMBER(4)")
                        .HasColumnName("NR_OFFSET");

                    b.Property<long>("ProtocoloId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PROTOCOLO");

                    b.Property<int>("Repeticoes")
                        .HasPrecision(3)
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("NR_REPETICOES");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_TIPO_CUIDADO");

                    b.Property<string>("UnidadeIntervalo")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TP_UNIDADE_INTERVALO");

                    b.Property<string>("UnidadeOffset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TP_UNIDADE_OFFSET");

                    b.HasKey("Id")
                        .HasName("PK_T_PB_REGRA_PROTOCOLO");

                    b.HasIndex("ProtocoloId");

                    b.ToTable("T_PB_REGRA_PROTOCOLO", null, t =>
                        {
                            t.HasCheckConstraint("CK_REGPROT_ANCORA", "TP_DATA_BASE IN ('NASCIMENTO','DATA_CIRURGIA','ULTIMA_REALIZACAO')");

                            t.HasCheckConstraint("CK_REGPROT_RECORRENCIA", "(NR_INTERVALO IS NULL AND TP_UNIDADE_INTERVALO IS NULL) OR (NR_INTERVALO IS NOT NULL AND TP_UNIDADE_INTERVALO IS NOT NULL)");

                            t.HasCheckConstraint("CK_REGPROT_REPETICOES", "NR_REPETICOES >= 1");

                            t.HasCheckConstraint("CK_REGPROT_TIPO", "TP_TIPO_CUIDADO IN ('VACINACAO','VERMIFUGACAO','EXAME','RETORNO','CIRURGIA','MEDICACAO','HIGIENE')");

                            t.HasCheckConstraint("CK_REGPROT_UNID_INTERV", "TP_UNIDADE_INTERVALO IN ('DIAS','SEMANAS','MESES')");

                            t.HasCheckConstraint("CK_REGPROT_UNID_OFFSET", "TP_UNIDADE_OFFSET IN ('DIAS','SEMANAS','MESES')");
                        });
                });

            modelBuilder.Entity("PetBuddies_API.Domain.Entities.OfertaEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Domain.Entities.ProtocoloEntity", "Protocolo")
                        .WithMany()
                        .HasForeignKey("ProtocoloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_OFERTA_PROTOCOLO");

                    b.Navigation("Protocolo");
                });

            modelBuilder.Entity("PetBuddies_API.Domain.Entities.RegraProtocoloEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Domain.Entities.ProtocoloEntity", "Protocolo")
                        .WithMany("Regras")
                        .HasForeignKey("ProtocoloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_REGPROT_PROTOCOLO");

                    b.Navigation("Protocolo");
                });

            modelBuilder.Entity("PetBuddies_API.Domain.Entities.ProtocoloEntity", b =>
                {
                    b.Navigation("Regras");
                });
#pragma warning restore 612, 618
        }
    }
}
