// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetBuddies_API.Data;

#nullable disable

namespace PetBuddies_API.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetBuddies_API.Models.AnimalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alergias")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_ALERGIA");

                    b.Property<bool>("Castrado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CT_CASTRADO");

                    b.Property<bool>("CondicaoCronica")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("CN_CONDICAO_CRONICA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_DATA_NASCIMENTO");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ES_ESPECIE");

                    b.Property<string>("Foto")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("FT_FOTO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME_ANIMAL");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_OBSERVACOES");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("NR_PESO");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("PT_PORTE");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("RC_RACA");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("SX_SEXO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("T_PB_ANIMAL");
                });

            modelBuilder.Entity("PetBuddies_API.Models.CheckinExtracaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CHECKIN_EXTRACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckinTratamentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CHECKIN_TRATAMENTO");

                    b.Property<string>("CodigoCongelado")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("CD_CODIGO_CONGELADO");

                    b.Property<int>("CondicaoClinicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONDICAO_CLINICA");

                    b.Property<decimal>("Confianca")
                        .HasColumnType("NUMBER(5,4)")
                        .HasColumnName("NR_CONFIANCA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<bool?>("ValorBooleano")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("BL_VALOR_BOOLEANO");

                    b.Property<decimal?>("ValorNumerico")
                        .HasColumnType("NUMBER(10,3)")
                        .HasColumnName("NR_VALOR_NUMERICO");

                    b.HasKey("Id");

                    b.HasIndex("CheckinTratamentoId");

                    b.HasIndex("CondicaoClinicaId");

                    b.ToTable("T_PB_CHECKIN_EXTRACAO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.CheckinResultadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CHECKIN_RESULTADO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckinTratamentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CHECKIN_TRATAMENTO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("DataReferencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_REFERENCIA");

                    b.Property<string>("Desfecho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_DESFECHO");

                    b.Property<decimal?>("DoseAplicada")
                        .HasColumnType("NUMBER(8,3)")
                        .HasColumnName("NR_DOSE_APLICADA");

                    b.Property<int>("PrescricaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRESCRICAO");

                    b.Property<int?>("RegraAplicadaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGRA_APLICADA");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("CheckinTratamentoId");

                    b.HasIndex("RegraAplicadaId");

                    b.HasIndex("PrescricaoId", "DataReferencia")
                        .IsUnique();

                    b.ToTable("T_PB_CHECKIN_RESULTADO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.CheckinTratamentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CHECKIN_TRATAMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Narrativa")
                        .IsRequired()
                        .HasColumnType("CLOB")
                        .HasColumnName("TX_NARRATIVA");

                    b.Property<string>("ObservacoesGerais")
                        .HasColumnType("CLOB")
                        .HasColumnName("TX_OBSERVACOES_GERAIS");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DH_REGISTRADO_EM");

                    b.Property<string>("TicUtilizada")
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DS_TIC_UTILIZADA");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId", "RegistradoEm");

                    b.ToTable("T_PB_CHECKIN_TRATAMENTO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ClinicaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("NR_CNPJ");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("NVARCHAR2(254)")
                        .HasColumnName("EM_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME_CLINICA");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TL_TELEFONE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("T_PB_CLINICA");
                });

            modelBuilder.Entity("PetBuddies_API.Models.CondicaoClinicaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONDICAO_CLINICA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("AT_ATIVO");

                    b.Property<int>("ClinicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("CD_CODIGO");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<bool>("Critica")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("FL_CRITICA");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_FONTE");

                    b.Property<string>("Rotulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_ROTULO");

                    b.Property<string>("TipoValor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_VALOR");

                    b.Property<string>("Unidade")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_UNIDADE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<int>("VeterinarioAutorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO_AUTOR");

                    b.HasKey("Id");

                    b.HasIndex("VeterinarioAutorId");

                    b.HasIndex("ClinicaId", "Codigo")
                        .IsUnique();

                    b.ToTable("T_PB_CONDICAO_CLINICA");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ConsultaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DH_DATA_HORA");

                    b.Property<string>("Motivo")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MT_MOTIVO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_OBSERVACAO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ST_STATUS_CONSULTA");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_TIPO_CONSULTA");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("T_PB_CONSULTA");
                });

            modelBuilder.Entity("PetBuddies_API.Models.JanelaAtendimentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_JANELA_ATENDIMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DH_DATA_HORA_INICIO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.HasIndex("VeterinarioId", "DataHoraInicio")
                        .IsUnique();

                    b.ToTable("T_PB_JANELA_ATENDIMENTO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.PrescricaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRESCRICAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("DataInicio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DT_INICIO");

                    b.Property<decimal>("DoseMax")
                        .HasColumnType("NUMBER(8,3)")
                        .HasColumnName("NR_DOSE_MAX");

                    b.Property<decimal>("DoseMin")
                        .HasColumnType("NUMBER(8,3)")
                        .HasColumnName("NR_DOSE_MIN");

                    b.Property<int>("DuracaoDias")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_DURACAO_DIAS");

                    b.Property<int>("FrequenciaDia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_FREQUENCIA_DIA");

                    b.Property<int?>("MaterialOrigemId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MATERIAL_ORIGEM");

                    b.Property<string>("Medicamento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_MEDICAMENTO");

                    b.Property<string>("Orientacao")
                        .HasColumnType("CLOB")
                        .HasColumnName("TX_ORIENTACAO");

                    b.Property<int>("RegistroAtendimentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGISTRO_ATENDIMENTO");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DS_UNIDADE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<int?>("VersaoOrigem")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_VERSAO_ORIGEM");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("RegistroAtendimentoId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("T_PB_PRESCRICAO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ProcedimentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PROCEDIMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnexosUrl")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("AN_ANEXOS_URL");

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<DateTime>("DataPrevistaFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_DATA_PREVISTA_FIM");

                    b.Property<DateTime>("DataPrevistaInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_DATA_PREVISTA_INICIO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_OBSERVACAO");

                    b.Property<int>("RegistroAtendimentoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGISTRO_ATENDIMENTO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ST_STATUS_PROCEDIMENTO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_TIPO_PROCEDIMENTO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("RegistroAtendimentoId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("T_PB_PROCEDIMENTO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.RegistroAtendimentoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGISTRO_ATENDIMENTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Anamnese")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("AN_ANAMNESE");

                    b.Property<int>("AnimalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ANIMAL");

                    b.Property<int>("ConsultaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONSULTA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<DateTime>("DataAtendimento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_DATA_ATENDIMENTO");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DG_DIAGNOSTICO");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OB_OBSERVACAO");

                    b.Property<string>("ProximaVacina")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PR_PROXIMA_VACINA");

                    b.Property<string>("ProximoRetorno")
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PR_PROXIMO_RETORNO");

                    b.Property<string>("Tratamento")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TR_TRATAMENTO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("ConsultaId")
                        .IsUnique();

                    b.ToTable("T_PB_REGISTRO_ATENDIMENTO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.RegraPrescricaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGRA_PRESCRICAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_ACAO");

                    b.Property<int>("CondicaoClinicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CONDICAO_CLINICA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("FonteCongelada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_FONTE_CONGELADA");

                    b.Property<decimal?>("Limite")
                        .HasColumnType("NUMBER(10,3)")
                        .HasColumnName("NR_LIMITE");

                    b.Property<int?>("Operador")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TP_OPERADOR");

                    b.Property<int>("Ordem")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_ORDEM");

                    b.Property<int>("PrescricaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_PRESCRICAO");

                    b.Property<string>("RotuloCongelado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_ROTULO_CONGELADO");

                    b.Property<string>("TipoValorCongelado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TP_VALOR_CONGELADO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("CondicaoClinicaId");

                    b.HasIndex("PrescricaoId");

                    b.ToTable("T_PB_REGRA_PRESCRICAO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ResponsavelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RESPONSAVEL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("NVARCHAR2(254)")
                        .HasColumnName("EM_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME_RESPONSAVEL");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TL_TELEFONE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.ToTable("T_PB_RESPONSAVEL");
                });

            modelBuilder.Entity("PetBuddies_API.Models.VeterinarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_VETERINARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("AT_ATIVO");

                    b.Property<int>("ClinicaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_CLINICA");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CA_CREATED_AT");

                    b.Property<string>("Crmv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NR_CRMV");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("NVARCHAR2(254)")
                        .HasColumnName("EM_EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_NOME_VETERINARIO");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("AT_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("ClinicaId");

                    b.HasIndex("Crmv")
                        .IsUnique();

                    b.ToTable("T_PB_VETERINARIO");
                });

            modelBuilder.Entity("PetBuddies_API.Models.AnimalEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.ResponsavelEntity", "Responsavel")
                        .WithMany("Animais")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("PetBuddies_API.Models.CheckinExtracaoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.CheckinTratamentoEntity", "CheckinTratamento")
                        .WithMany("Extracoes")
                        .HasForeignKey("CheckinTratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.CondicaoClinicaEntity", "CondicaoClinica")
                        .WithMany()
                        .HasForeignKey("CondicaoClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckinTratamento");

                    b.Navigation("CondicaoClinica");
                });

            modelBuilder.Entity("PetBuddies_API.Models.CheckinResultadoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.CheckinTratamentoEntity", "CheckinTratamento")
                        .WithMany("Resultados")
                        .HasForeignKey("CheckinTratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.PrescricaoEntity", "Prescricao")
                        .WithMany()
                        .HasForeignKey("PrescricaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.RegraPrescricaoEntity", "RegraAplicada")
                        .WithMany()
                        .HasForeignKey("RegraAplicadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CheckinTratamento");

                    b.Navigation("Prescricao");

                    b.Navigation("RegraAplicada");
                });

            modelBuilder.Entity("PetBuddies_API.Models.CheckinTratamentoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.AnimalEntity", "Animal")
                        .WithMany("Checkins")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PetBuddies_API.Models.CondicaoClinicaEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.ClinicaEntity", "Clinica")
                        .WithMany("CondicoesClinicas")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.VeterinarioEntity", "VeterinarioAutor")
                        .WithMany()
                        .HasForeignKey("VeterinarioAutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinica");

                    b.Navigation("VeterinarioAutor");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ConsultaEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.AnimalEntity", "Animal")
                        .WithMany("Consultas")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.VeterinarioEntity", "Veterinario")
                        .WithMany("Consultas")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetBuddies_API.Models.JanelaAtendimentoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.ConsultaEntity", "Consulta")
                        .WithMany()
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PetBuddies_API.Models.VeterinarioEntity", "Veterinario")
                        .WithMany("JanelasAtendimento")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetBuddies_API.Models.PrescricaoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.AnimalEntity", "Animal")
                        .WithMany("Prescricoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.RegistroAtendimentoEntity", "RegistroAtendimento")
                        .WithMany()
                        .HasForeignKey("RegistroAtendimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.VeterinarioEntity", "Veterinario")
                        .WithMany()
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("RegistroAtendimento");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ProcedimentoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.AnimalEntity", "Animal")
                        .WithMany("Procedimentos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.RegistroAtendimentoEntity", "RegistroAtendimento")
                        .WithMany("Procedimentos")
                        .HasForeignKey("RegistroAtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.VeterinarioEntity", "Veterinario")
                        .WithMany("Procedimentos")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("RegistroAtendimento");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("PetBuddies_API.Models.RegistroAtendimentoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.AnimalEntity", "Animal")
                        .WithMany("RegistroAtendimentos")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.ConsultaEntity", "Consulta")
                        .WithOne("RegistroAtendimento")
                        .HasForeignKey("PetBuddies_API.Models.RegistroAtendimentoEntity", "ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("PetBuddies_API.Models.RegraPrescricaoEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.CondicaoClinicaEntity", "CondicaoClinica")
                        .WithMany()
                        .HasForeignKey("CondicaoClinicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetBuddies_API.Models.PrescricaoEntity", "Prescricao")
                        .WithMany("Regras")
                        .HasForeignKey("PrescricaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CondicaoClinica");

                    b.Navigation("Prescricao");
                });

            modelBuilder.Entity("PetBuddies_API.Models.VeterinarioEntity", b =>
                {
                    b.HasOne("PetBuddies_API.Models.ClinicaEntity", "Clinica")
                        .WithMany("Veterinarios")
                        .HasForeignKey("ClinicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PetBuddies_API.Models.AnimalEntity", b =>
                {
                    b.Navigation("Checkins");

                    b.Navigation("Consultas");

                    b.Navigation("Prescricoes");

                    b.Navigation("Procedimentos");

                    b.Navigation("RegistroAtendimentos");
                });

            modelBuilder.Entity("PetBuddies_API.Models.CheckinTratamentoEntity", b =>
                {
                    b.Navigation("Extracoes");

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ClinicaEntity", b =>
                {
                    b.Navigation("CondicoesClinicas");

                    b.Navigation("Veterinarios");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ConsultaEntity", b =>
                {
                    b.Navigation("RegistroAtendimento");
                });

            modelBuilder.Entity("PetBuddies_API.Models.PrescricaoEntity", b =>
                {
                    b.Navigation("Regras");
                });

            modelBuilder.Entity("PetBuddies_API.Models.RegistroAtendimentoEntity", b =>
                {
                    b.Navigation("Procedimentos");
                });

            modelBuilder.Entity("PetBuddies_API.Models.ResponsavelEntity", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("PetBuddies_API.Models.VeterinarioEntity", b =>
                {
                    b.Navigation("Consultas");

                    b.Navigation("JanelasAtendimento");

                    b.Navigation("Procedimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
