-- =============================================================
-- PetBuddies-API — Seed base obrigatório para o bot funcionar
-- Executar ANTES de qualquer teste E2E via WhatsApp.
-- Ordem: Endereco → Clinica → TipoAnimal
-- =============================================================

-- 1. ENDERECO da clínica (referenciado pela Clinica, id=1)
INSERT INTO T_PB_ENDERECO (
    ID_ENDERECO, LG_LOGRADOURO, NR_NUMERO, CD_CIDADE,
    ES_ESTADO, NR_CEP, CA_CREATED_AT
) VALUES (
    1, 'Avenida Paulista', '1000', 'São Paulo',
    'SP', '01310100', CURRENT_TIMESTAMP
);

-- 2. CLINICA (id=1 hardcoded em ResponsavelService.ClinicaId)
INSERT INTO T_PB_CLINICA (
    ID_CLINICA, NM_NOME_CLINICA, NR_CNPJ, TL_TELEFONE,
    ID_ENDERECO, CA_CREATED_AT
) VALUES (
    1, 'PetBuddies Clínica Veterinária', '00000000000000', '11999990000',
    1, CURRENT_TIMESTAMP
);

-- 3. TIPO_ANIMAL — todas as combinações válidas de Especie + Porte
-- Enums armazenados como string (ApplicationContext.OnModelCreating → SetProviderClrType(string))
-- Raca vazia para animais cadastrados via bot (decisão D4)

-- CACHORRO
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (1,  'CACHORRO', 'MINI',    '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (2,  'CACHORRO', 'PEQUENO', 'SEM_RACA', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (3,  'CACHORRO', 'MEDIO',   '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (4,  'CACHORRO', 'GRANDE',  '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (5,  'CACHORRO', 'GIGANTE', 'SEM_RACA', CURRENT_TIMESTAMP);
-- GATO
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (6,  'GATO',    'MINI',    '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (7,  'GATO',    'PEQUENO', 'SEM_RACA', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (8,  'GATO',    'MEDIO',   '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (9,  'GATO',    'GRANDE',  '', CURRENT_TIMESTAMP);
-- PASSARO
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (10, 'PASSARO', 'MINI',    '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (11, 'PASSARO', 'PEQUENO', 'SEM_RACA', CURRENT_TIMESTAMP);
-- COELHO
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (12, 'COELHO',  'MINI',    '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (13, 'COELHO',  'PEQUENO', 'SEM_RACA', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (14, 'COELHO',  'MEDIO',   '', CURRENT_TIMESTAMP);
-- HAMSTER
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (15, 'HAMSTER', 'MINI',    '', CURRENT_TIMESTAMP);
-- OUTRO
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (16, 'OUTRO',   'MINI',    '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (17, 'OUTRO',   'PEQUENO', 'SEM_RACA', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (18, 'OUTRO',   'MEDIO',   '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (19, 'OUTRO',   'GRANDE',  '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (20, 'OUTRO',   'GIGANTE', 'SEM_RACA', CURRENT_TIMESTAMP);

COMMIT;
