-- Seed T_PB_TIPO_ANIMAL
-- Todas as combinações válidas de Especie + Porte para o bot poder cadastrar animais.
-- Enums armazenados como string (ApplicationContext.OnModelCreating → SetProviderClrType(string)).
-- Raca vazia — padrão para animais cadastrados via WhatsApp (decisão D4).

INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (1,  'CACHORRO', 'MINI',     '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (2,  'CACHORRO', 'PEQUENO',  '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (3,  'CACHORRO', 'MEDIO',    '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (4,  'CACHORRO', 'GRANDE',   '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (5,  'CACHORRO', 'GIGANTE',  '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (6,  'GATO',     'MINI',     '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (7,  'GATO',     'PEQUENO',  '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (8,  'GATO',     'MEDIO',    '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (9,  'GATO',     'GRANDE',   '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (10, 'PASSARO',  'MINI',     '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (11, 'PASSARO',  'PEQUENO',  '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (12, 'COELHO',   'MINI',     '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (13, 'COELHO',   'PEQUENO',  '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (14, 'COELHO',   'MEDIO',    '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (15, 'HAMSTER',  'MINI',     '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (16, 'OUTRO',    'MINI',     '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (17, 'OUTRO',    'PEQUENO',  '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (18, 'OUTRO',    'MEDIO',    '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (19, 'OUTRO',    'GRANDE',   '', CURRENT_TIMESTAMP);
INSERT INTO T_PB_TIPO_ANIMAL (ID_TIPO_ANIMAL, ES_ESPECIE, PT_PORTE, RC_RACA, CA_CREATED_AT) VALUES (20, 'OUTRO',    'GIGANTE',  '', CURRENT_TIMESTAMP);

COMMIT;
